### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by dariarostshina** [mailru/jira-plugins-jsincluder#1]
- [ ] Search by issue key
- [ ] Search by script name, projects and script code
- [ ] Redesign binding context

**Comment by filantus** [comment]
При создании биндингов, в пикере проектов, нужна возможность указывать их по ключам. Сейчас можно только по полному названию, что не удобно т.к. они бывают длинными, состоящими из нескольких слов, содержащие спецсимволы и т.д.
