### ISSUE TITLE
JS not applying UI on CREATE screen when initiated from specific location

### ISSUE THREAD

**Issue by tovap** [mailru/jira-plugins-jsincluder#11]
As per the user needs, I use the JSIncluder addon for changing the text of  locked custom fields:
Epic Name - to - Feature Name
Epic Link - to Feature Link

I created different scripts for the different screens.
for example - for changing "Epic Link" to "Feature Link" on Story view screen:
AJS.$(document).ready(function () {document.querySelector('[title="Epic Link"]').innerHTML = "Feature Link"})  
 or - 
for changing "Epic Name" to "Feature Name" on Create screen:
AJS.$(document).ready(function () {document.querySelector('[for="customfield_10002"]').innerHTML = "Feature Name"});

Everything works fine. except when I initiate the Create screen from the Indexing page:
If I go to Admin tools>System>Indexing
and hit the CREATE button - 
the JS won't apply and the text of the fields does not change
PFA screensots

I tried to add this code:

AJS.$('.create-issue').on('click',function(){
document.querySelector('[for="customfield_10002"]').innerHTML = "Feature Name"
}) 
but with no help.

Your advise will be really appreciated.
Thanks
Tova

JS not updating UI
![js not updateing ui](https://user-images.githubusercontent.com/36586787/36351979-29c98362-14ba-11e8-8069-b8f08efa8d70.PNG)
JS updating UI
![js updates ui](https://user-images.githubusercontent.com/36586787/36351981-2a0f0dce-14ba-11e8-8a00-7c0c3d5830db.PNG)
(that's the only location I could reproduce so far, maybe there are more locations)

**Comment by tovap** [comment]
Another issue I've tracked:
I'm trying to change the word "Epic" to "Feature" on this DDL on the issues list view
![image](https://user-images.githubusercontent.com/36586787/36352522-d7541684-14c2-11e8-831e-14aa2afeab20.png)
Using, for ex., this code:
AJS.$(document).ready(function () {
document.querySelector('[title="Epic Name"]').querySelector("em").innerHTML = "Feature Name"
})    
but it does not work.

The same when I'm trying to change the titles of the columns
from "Epic Link" to "Feature Link"
![image](https://user-images.githubusercontent.com/36586787/36352567-7ef1788c-14c3-11e8-9649-76fda15e86ef.png)
using the code:
AJS.$(document).ready(function () {
if(document.querySelector('[title="Sort By Epic Link"]')!=null)
	document.querySelector('[title="Sort By Epic Link"]').innerHTML = "Feature Link"
})   
It does not work

Is the addon built for making changes throughout all the web-app? or only on the create/view/edit/transition screens?

**Comment by dariarostshina** [comment]
Hello!

Thanks for a bug report.
First, I fixed bug. You may download a new version https://marketplace.atlassian.com/plugins/ru.mail.jira.plugins.jsincluder/versions#b200100230
Second, js works only on the create/view/edit/transition screens.

Best regards,
Dariya

**Comment by tovap** [comment]
Hi Daria,
Thanks a lot for the fix and for the update.
I’ll download the new version and let you know if it fixed the issue.
Thanks
Tova

With regards –
Tova Pozen
[cid:image001.png@01D35B87.B99F8C30]

**Comment by tovap** [comment]
Hi Daria
Thanks again for your great addon and excellent support.

While using on the addon, I’ve noticed one more issue:
We have Structure installed, and on the quick-view issue screen initiated on the Structure segment, for issue type Feature -  the JS from the JSIncluder – won’t run/reflect.
See on the screenshot - the field "Epic Name" does not change to "Feature Name" as it does in any other place.
![image](https://user-images.githubusercontent.com/36586787/37029849-7560ec64-2141-11e8-9300-f1528563b57c.png)


Is that a bug ? Or there is something wrong in my script?

Here is my script:
AJS.$(document).ready(function () {
if(document.querySelector('[title="Epic Name"]')!=null)
	document.querySelector('[title="Epic Name"]').innerHTML = "Feature Name"
})   

and the Bindings are:
All projects
Issue type: fearure
Screen: view

Please advise.
Thanks!

Tova Pozen

**Comment by needI2001** [comment]
Hi Daria, 

I have also to confirm this issue, described at the first post. 

It's really simple to reproduce: 
Just create on any project and issue type an javascript alert popup. (just for testing, something like "hello world")

You're gonna see two behaviors: 

1. While you are opening an issue and the issue creator popup appears, everything will work fine -> as expected.
2. If you are in the admin section (e.g "System->System info") and you will open a new issue it will not open a popup box (known from behavior 1) rather you are beeing linked to a new website. At this "let us call it native jira site" your implemented javascript do not work.

So to make it easy to understand: Javascript Code which was implemented with JSINCLUDER works in the popup window of jira but not on the "native" page.

Is it understandable?

**Comment by dariarostshina** [comment]
@needI2001 Hello!
I don't reproduce it on the "native" page. When i open create issue in new tab it's works fine. What version of the plugin you have installed?

**Comment by dariarostshina** [comment]
@tovap Hello!
I checked working our plugin in Structure and it's works fine. Maybe is something wrong in your script.

**Comment by tovap** [comment]
Hi Daria
Thanks for your reply.
                When i open create issue in new tab it's works fine
You are right. The issue is on the “quick-view” screen. When you stand on the issue in the left-sie navigator, on the right-side there is a quick-view window. There – the script won’t run.

[cid:image002.png@01D3BA09.9CAAFD40]

Our script-runner version is a 5.2.2

With regards –
Tova Pozen

**Comment by dariarostshina** [comment]
@tovap 
I check it in quick view.
<img width="1275" alt="2018-03-12 15 10 13" src="https://user-images.githubusercontent.com/13033838/37283042-9a6cb126-2607-11e8-946e-17a04c6493ba.png">
I changed name for field Labels.
This is my script:
AJS.$(document).ready(function () {
   if(jQuery('#wrap-labels .name')!=null)
       jQuery('#wrap-labels .name').text("LABELS:")
})

**Comment by tovap** [comment]
Great!
This solved the issue for me.
I used your code, just replaced the element id:

AJS.$(document).ready(function () {
if(jQuery('#rowForcustomfield_10002 .name')!=null)
jQuery('#rowForcustomfield_10002 .name').text("Feature Name:")
})

You are the best!
Thanks!

With regards –
Tova Pozen

**Comment by dariarostshina** [comment]
Ok)))) Then I close the task.

**Comment by tovap** [comment]
Hi Daria
Sorry to open the thread again, but I've detected another issue:
When I edit fields locally on the VIEW screen, after saving the change - it seems like the page is re-renders but the JS is not applied.
For ex:
Edit locally the "Description" field (Note that at this stage the field "Epic Name" is applied by the JS and showed as "Feature Name")
![image](https://user-images.githubusercontent.com/36586787/38777224-190f7f12-40ad-11e8-88c4-180f22096d3c.png)
![image](https://user-images.githubusercontent.com/36586787/38777175-56360e98-40ac-11e8-915f-83f8137cbde0.png)
After Saving the change the filed is changing back to "Epic Name"
![image](https://user-images.githubusercontent.com/36586787/38777196-afd399f2-40ac-11e8-945f-5b53a3e7e77f.png)
After refreshing the page the JS will aplly again, but it's quite essential that the JS will apply in any situation.
Is that something you can cover?

Thanks a lot
Tova

**Comment by tovap** [comment]
Hi Daria,

Just checking to see if you have any update for me.

Thanks!
Tova
