### ISSUE TITLE
Jira 8.5.x - formatter is not defined

### ISSUE THREAD

**Issue by voelda** [mailru/jira-plugins-jsincluder#13]
When trying to move cards on Kanban or Scrum Board the following JavaScript Error occurs when JSIncluder is enabled (Jira Software Server 8.5.1, JSIncluder 2.1.7): 

> Details
Exception: Uncaught ReferenceError: formatter is not defined
Resource: https://jira/s/2d404c1504d9c23cdcd0c7e700240be2-CDN/1z9c0j/805001/77eb8cfb6c4002688b84515132503d70/416b56c113aa6da5b768ff4547c51613/_/download/contextbatch/js/gh-rapid-work,atl.general,greenhopper-rapid-non-gadget,jira.project.sidebar,jira.general,jira.global,com.atlassian.jira.projects.sidebar.init,atl.global,-_super/batch.js?agile_global_admin_condition=true&baseurl-check-resources=true&extensiIoAbf=true&flexboards=true&healthcheck-resources=true&jag=true&jaguser=true&locale=de-DE&whisper-enabled=true
Line: 27195
Column: 31

Affected code seems to be the following: 
```javascript
var JS_INCLUDER = {
    CONTEXT_CREATE: 'create',
    CONTEXT_VIEW: 'view',
    CONTEXT_EDIT: 'edit',
    CONTEXT_TRANSITION: 'transition',

    _cache: {},
    params: {},
    $contextObject: null,

    _execute: function(scripts, params, context, $contextObject) {
        JS_INCLUDER.params = params;
        JS_INCLUDER.params.context = context;
        JS_INCLUDER.$contextObject = $contextObject;
        for (var i = 0; i < scripts.length; i++)
            try {
                eval(scripts[i].code);
            } catch (e) {
                console.error(formatter.format('Script: {0} \n Error: {1}', scripts[i].name, e.message));
                alert(e.message);
            }
    },
```

**Comment by mashintsev** [comment]
Hi, @voelda. 
We fixed it in 2.1.8 version. You can update plugin soon.
