### ISSUE TITLE
Need to support Jira 8.8.x

### ISSUE THREAD

**Issue by bra1ncramp** [mailru/jira-plugins-jsincluder#14]
Current build only supports Jira 8.5.1. Jira is currently up to 8.8.1, and this app is registering as incompatible.

**Comment by dariarostshina** [comment]
Hello, plugin support now Jira 8.8.1.

**Comment by bra1ncramp** [comment]
That's great, but Jira has monthly patches. They're at 8.11.1, now.

**Comment by dariarostshina** [comment]
Added compatibility with latest jira version.
