### ISSUE TITLE
Jsincluder stopped working

### ISSUE THREAD

**Issue by acasari** [mailru/jira-plugins-jsincluder#15]
Hi,
Jira version: v8.6.1
Jsincluder 2.1.8 

Jsincluder stopped working. The basic "Alert" script fails to show. This was working OK previously.
Tried to disable/enable , no luck.
The wierd thing is that for some users it works.
There is no error or warning in the jira logs nor in the browser console.

Any ideas?

**Comment by dariarostshina** [comment]
Hello!
Thanks for feedback, we will investigate this problem.

**Comment by acasari** [comment]
Hi,
I found the problem, it's this script that makes it fail. However the scripts works if you run it in the browser console. Do you see something wrong? I would like to use it from jsincluder.


[Remueve seccion Watch para el grupo externo jira-externos_cmf.txt](https://github.com/mailru/jira-plugins-jsincluder/files/4996247/Remueve.seccion.Watch.para.el.grupo.externo.jira-externos_cmf.txt)

**Comment by dariarostshina** [comment]
Hello, try this:

`function($){
    if (JS_INCLUDER.params.userDetails.groupNames.indexOf("jira-externos_cmf") !== -1) {
        $("#view-watcher-list").parents('dl').remove();
    }
})(AJS.$);`

**Comment by acasari** [comment]
Thanks for your help. That works.
