### ISSUE TITLE
Add servicedesk.portal contexts

### ISSUE THREAD

**Issue by darksidemilk** [mailru/jira-plugins-jsincluder#2]
It is possible to utilize your existing infrastructure to inject js into the service desk portal to fill in custom fields.
I did this myself and attached my jar file with the edited xml config file and a associated js file. (renamed it to .jar.zip just rename it and take out file extension)
[plugin.3469994663755724211.jsincluder-2.1.5.jar.zip](https://github.com/mailru/jira-plugins-jsincluder/files/554132/plugin.3469994663755724211.jsincluder-2.1.5.jar.zip)

I did this with the goal (which is now achieved) of getting the computer name of a local client making a ticket and setting that value to a custom field called Computer name. I had to inspect the element of the custom field in the portal form to get its id and element name and such. But long story short, it works.

I would bet that you could easily add a service desk binding like the project bindings. Or just add it as an option for project page bindings.

I utilized these in creating this
https://answers.atlassian.com/questions/42371003/javascript-or-redirect-in-customer-portal
this may also be of use for adding to just create/view pages in the portal individually
https://developer.atlassian.com/jiradev/jira-applications/jira-service-desk/jira-service-desk-ui-plugin-points-customer-portal

p.s.
Thank you for making this amazing plugin.

**Comment by darksidemilk** [comment]
In case you don't feel like opening the jar archive....
I added this custom script to \ru\mail\jira\plugins\jsincluder\
`
/*
* @Author: jfullmer
* @Date:   2016-10-14 09:44:07
* @Last Modified by:   jfullmer
* @Last Modified time: 2016-10-24 14:50:36
*/

function getHost(jQuery) {    
	// Set the url with the php script with get params
	var url='http://arrowfs4/g.php';
	// Create an ajax stye request var
	var xhr = new XMLHttpRequest();
	// Open the php script and GET the hostname
	xhr.open('GET', url, true);
	// After send the ready state of xhr will change, 
	// set the computer name value when it does.
	xhr.onreadystatechange = function() {
		// Confirm the proper state
		if (xhr.readyState===4 && xhr.status===200) {	
			document.getElementById("customfield_16202").value = xhr.responseText;
		}
	};
	// send the request
	xhr.send();    
	return;
}

// https://swizec.com/blog/how-to-properly-wait-for-dom-elements-to-show-up-in-modern-browsers/swizec/6663
function tryThis() {
	if (!AJS.$(document.getElementById("customfield_16202")).size()) {
		window.requestAnimationFrame(tryThis);
	}
	AJS.$(getHost);
};

AJS.$(tryThis);
`

And I added this line at the end of  atlassian-plugin.xml

`
	<web-resource key="portal-custom">
		<resource name="getHost.js" type="download" location="ru/mail/jira/plugins/jsincluder/getHost.js"/>
		<context>servicedesk.portal</context>
	</web-resource>
`
It seems to me that you could utilize the servicedesk contexts to add that binding to the customer portal.

**Comment by dariarostshina** [comment]
Hello!
At the moment, we do not view the inclusion of scripts in the servicedesk.portal as a special case.
You can modify the plug-in yourself.  Also, scripts can be connected via announcement banner.

**Comment by dariarostshina** [comment]
Hello!

We added it. Please download the last version of plugin.
