### ISSUE TITLE
Cannot edit or add scripts in Jira 8.12

### ISSUE THREAD

**Issue by bra1ncramp** [mailru/jira-plugins-jsincluder#20]
After updating to Jira 8.12.0, existing scripts appear to work, but the "Edit" in Manage Apps -> JSIncluder does not work, and the + Add Script button does not work.

**Comment by bra1ncramp** [comment]
New version (2.2.2) does not fix this problem

**Comment by dariarostshina** [comment]
Hello, it fixed in 2.2.3 version
