### ISSUE TITLE
JsIncluder 2.2.5 not working anymore on Jira 8.5.8

### ISSUE THREAD

**Issue by voelda** [mailru/jira-plugins-jsincluder#23]
Since Upgrade to JSIncluder 2.2.5 we get the following errors, scripts aren't working anymore: 

> batch.js?locale=de-DE:188 Failed to run init function: Cannot set property 'context' of undefined ƒ () {
>             var issueId = $('#key-val').attr('rel');
>             if (issueId)
>                 JS_INCLUDER.executeIssueScripts(issueId, JS_INCLUDER.CONTEXT_VIEW, $(document));
> 
>             Events… TypeError: Cannot set property 'context' of undefined
>     at Object._execute (batch.js:39)
>     at Object.executeIssueScripts (batch.js:79)
>     at batch.js?agile_global_admin_condition=true&baseurl-check-resources=true&healthcheck-resources=true&jag=true&jaguser=true&jira.create.linked.issue=true&locale=de-DE&richediton=true:11368
>     at batch.js?locale=de-DE:292 TypeError: Cannot set property 'context' of undefined
>     at Object._execute (https://jira/s/d41d8cd98f00b204e9800998ecf8427e-CDN/zaizs7/805008/62e7f91cc17290c79ae9e70b1ff8a826/ec252de965a875cc75cc416048c450a9/_/download/contextbatch/js/jira.general,-_super/batch.js:39:36)
>     at Object.executeIssueScripts (https://jira/s/d41d8cd98f00b204e9800998ecf8427e-CDN/zaizs7/805008/62e7f91cc17290c79ae9e70b1ff8a826/ec252de965a875cc75cc416048c450a9/_/download/contextbatch/js/jira.general,-_super/batch.js:79:21)
>     at https://jira/s/75314acf3649fb7182e243cdbc582741-CDN/zaizs7/805008/62e7f91cc17290c79ae9e70b1ff8a826/24d78281ea55985774d098b0425c0f5a/_/download/contextbatch/js/jira.browse.project,jira.view.issue,atl.general,project.issue.navigator,jira.global,atl.global,-_super/batch.js?agile_global_admin_condition=true&baseurl-check-resources=true&healthcheck-resources=true&jag=true&jaguser=true&jira.create.linked.issue=true&locale=de-DE&richediton=true:11368:29
>     at https://jira.com/s/21db4998c04c578add6f9a4347fafa04-CDN/zaizs7/805008/62e7f91cc17290c79ae9e70b1ff8a826/2d6959d1751f95522cbb7bddea9d32ae/_/download/contextbatch/js/_super/batch.js?locale=de-DE:292:488

Kind regards

**Comment by mashintsev** [comment]
Check 2.3.1 version
