### ISSUE TITLE
When creating issue from board, the scripts are not executed

### ISSUE THREAD

**Issue by t2consult** [mailru/jira-plugins-jsincluder#3]
Steps to reproduce:

Create a new filter with JQL:
issueType!=Bug

Create a new Scrum-Board based on the recently created filter.
When using the create issue button at the very bottom of the backlog:
![image](https://cloud.githubusercontent.com/assets/1218878/20314835/e36a7e80-ab5b-11e6-85db-4b6cb01edaf2.png)

There will be the following message when creating on top of creating the issue:
![image](https://cloud.githubusercontent.com/assets/1218878/20314852/fd0e64fa-ab5b-11e6-8462-c0ac047303da.png)

Translated:
`Due to the configuration for this particular board, you'll have to use the full dialog to create a new issue. Learn more`

This dialog won't be calling any Javascript according to the rules defined in jsIncluder.

Best regards,
Tobias

**Comment by dariarostshina** [comment]
Hello!
Thank you very much for the detailed description of the problem.
The next release is required to correct this error.

**Comment by t2consult** [comment]
Hi Daria,
thank you for your input: Will there be a new release of jsIncluder or are you suggesting an update of JIRA?

**Comment by dariarostshina** [comment]
Hello!
New version is available on marketplace https://marketplace.atlassian.com/plugins/ru.mail.jira.plugins.jsincluder/versions

**Comment by t2consult** [comment]
Hello Daria,
thank you so much for the quick help on this.
I can confirm that the issue is fixed in the new version 2.0.7.

Best regards,
Tobias
