### ISSUE TITLE
CSS added to Edit binding works on Transition as well

### ISSUE THREAD

**Issue by bugza** [mailru/jira-plugins-jsincluder#30]
How to reproduce:

Create a CSS script and associate with some project **Edit** binding. For example, CSS that removes Comment section on the dialog window: 

div.field-group.aui-field-wikiedit, sd-comment-field, label[for="comment"] { 
  display:none;
}

If you will open an issue in the project and will select a **Transition** with a screen, you will see a **Comment** section.
If you will open after **Edit** dialog, you will not see a **Comment** section. 
It is OK and works as configured, BUT if you will open any **Transition** with a screen after **Edit** dialog opening, the **Comment** section will disappear. 

The **Comment** section in **Transition** will be available after the page reload only.

**Comment by dariarostshina** [comment]
Fixed this, check a new version
