### ISSUE TITLE
JsIncluder does not work when I am not logged into JIRA

### ISSUE THREAD

**Issue by t2consult** [mailru/jira-plugins-jsincluder#4]
Hi there,

we have a project on which we allow anonymous users to create issues.

Unfortunately JsIncluder gives us the following exception in the Logs:
`GET https://jira.iservices.db.de/rest/jsincluder/1.0/controller/getCreateScripts?projectId=11600&issueTypeId=11000&_=1481708637142 401 (Unauthorized)`

We have a workaround by using "the old style way" of putting these scripts in the Field-Description of a field we are just using for specific issue type.

But it would be great to have this issue resolved in a future Version of JsIncluder.

Best regards,
Tobias

**Comment by dariarostshina** [comment]
Hello!
Thanks for this issue!
Maybe it will be implemented in the next version.

**Comment by dariarostshina** [comment]
Hello!
The new 2.0.8 version is available at https://marketplace.atlassian.com/plugins/ru.mail.jira.plugins.jsincluder/versions

**Comment by t2consult** [comment]
Hi Daria,
thank you so much for this quick fix you supplied.
I have just installed 2.0.8. and it's working perfectly.
Best regards,
Tobias
