### ISSUE TITLE
JSic

### ISSUE THREAD

**Issue by bugza** [mailru/jira-plugins-jsincluder#45]
For now JSIncluder only lacks 3 fetaure to be the best javascript includer for Jira. As well it would be very useful features for developing and supporting. Please 
1. Open the script Create/Edit dialog in a current tab as a **form**, not as a **dialog** window. Current dialog opening  as a dialog window limits a code screen and its functionality.
2. Add **Show code** bottom for code preview. For now to take a look on a script, we have to use **Edit** button. It is not save.
3. Add a possibility for a folders structure creating. 

Please take a look at scripts previewing/editing/creating and a folder structure creating, as it already done, in **MyGroovy Workflow script registry**. It just perfect. Why you do not use the same approach/functionalities in JSIncluder? 
By replacing the current JSIncluder script editing with MyGroovy script editing, you will resolve a lot of problems (screen resizing, for example).

Script preview/managing and folder managing view:
![3](https://user-images.githubusercontent.com/37148917/114998986-20643880-9eaa-11eb-8f72-6626b5a62344.png)

Script editing view:
![4](https://user-images.githubusercontent.com/37148917/114999090-35d96280-9eaa-11eb-8cf6-fef433b6667a.png)

**Comment by dariarostshina** [comment]
Hello,
this was added in latest version of plugin
