### ISSUE TITLE
Scripts not being called from Kanban and ScrumBoards

### ISSUE THREAD

**Issue by t2consult** [mailru/jira-plugins-jsincluder#5]
Hi - and a happy new year!

I have just found another issue where scripts are not being called from agile boards.
I have installed the most recent version 2.0.8.

Reproducing the issue should work, when you add a new Script working on a Test-Project (ProjectKey=TEST) and let it display the default "Hello World" Alert.

When you go to the search now by calling the following URL and choose "Detail View" the Alert is displayed correctly.
/browse/TEST-93?jql=project%3Dtest

When creating a board from these issues and go to the Backlog of the Board by visiting
/secure/RapidBoard.jspa?projectKey=TEST&rapidView=108
the script will not be called.
The rapidView-ID needs to be of course adjusted to the RapidBoard you created.

Best regards,
Tobias

**Comment by dariarostshina** [comment]
Hi Tobias!
A happy new year!
Thanks for this bug. We consider the solution of this problem in the next few weeks.

**Comment by dariarostshina** [comment]
Hello Tobias!
We fixed this bug. You may download a new version 2.0.10 from [this](https://marketplace.atlassian.com/plugins/ru.mail.jira.plugins.jsincluder/versions).

Best regards,
Daria
