### ISSUE TITLE
Issue type bindings are not respected when issue type is changed

### ISSUE THREAD

**Issue by RJanata** [mailru/jira-plugins-jsincluder#52]
Hi team,

when JS rules are bind to a specific issue type, then it stops working when the issue type is changed (JsIncluder still uses original issue type instead of the new one).

**Steps to reproduce:**
1. create binding to a specific issue type only (e.g. Task)
2. create a Task and make sure the JS script is executed - OK
3. change (move) the issue type from Task to something different (e.g. Bug)
4. make sure the JS script IS NOT executed - not OK (!)

**Result:** The JS script IS executed for the Bug (although no binding defined).

5. create a Story issue and change (move) it to Task
6. make sure the JS scirpt IS executed - not OK (!)

**Result:** The JS script IS NOT executed for the Bug (although binding for Task is defined).

**Expected result:**
The JsIncluder bindings should be respected after issue type change.

**Enviornment:**
* JIRA 7.3.4/JsIncluder 2.1.8
* JIRA 8.16.1/JsIncluder 2.5.0

Thanks,
Radek

**Comment by dariarostshina** [comment]
Hello,
thank you, we will fix this as soon as possible.

**Comment by dariarostshina** [comment]
Hello,
this was fixed in latest version
