### ISSUE TITLE
support in JIRA Data center and in JIRA server 18.x 

### ISSUE THREAD

**Issue by olgaplisko** [mailru/jira-plugins-jsincluder#56]
Please share your roadmap for new releases supported in in Jira DataCenter and in Jira Server 18.x
Thank you ahead,
Olga

**Comment by dariarostshina** [comment]
Hello Olga,
i updated compatibility for Jira 18.x and this version works fine on Data Center

**Comment by olgaplisko** [comment]
Hi Daria,
Thank you for the update and for your fast response.
Could you please also update Atlassian Marketplace regarding Data center
support.

Thanks,
Olga Plisko

**Comment by dariarostshina** [comment]
To add support to the marketplace, you need to go through a review with the Atlassian team. This is taking quite a long time and is not ready at the moment.
The version for Jira Server works stably and on the Data Center, even if it says that this version is not compatible.

**Comment by olgaplisko** [comment]
thank you for update
