### ISSUE TITLE
Script we use via JsIncluder not working on Internet Explorer

### ISSUE THREAD

**Issue by crazyalkolik** [mailru/jira-plugins-jsincluder#7]
Here is my script. Please tell me how to make it compatible with Internet Explorer 

jQuery( document ).ready(function() {
jQuery( ".multi-select-select").change(function() {
jQuery("#customfield_11203 > option").show();
jQuery("#customfield_11203").prop('selectedIndex',0);
///işe yarayan
var selected_data = jQuery( ".representation > ul > li .value-text" )[0].innerHTML.substr(0, 3);
//var selected_data = 'EBS';

jQuery("#customfield_11203").find('option').each(function() {

if(jQuery(this)[0].innerHTML.substr(0, 3) != selected_data){
//jQuery(this)[0].remove();
jQuery(this).hide();

}

});
  
    });
 });

**Comment by hellboy81** [comment]
Which version?
