### ISSUE TITLE
JSD: Banner on customer page

### ISSUE THREAD

**Issue by gonchik** [mailru/jira-plugins-jsincluder#8]
Hi! 

I wonder if jsincluder starts supported banner functionality for customer page side. 

For example: 
![photo5278704984097138676](https://user-images.githubusercontent.com/12548235/29925108-f8d4d488-8e67-11e7-8b70-cd9edf799f5e.jpg)

Reason is write a short instructions, or any static info. 

Thank you. 

If you want to ask additional info. 
Feel free for clarify. 

Best regards,
Gonchik Tsymzhitov

**Comment by gonchik** [comment]
Any plans?

**Comment by dariarostshina** [comment]
Hello!
Excuse me for the long answer.
We turn to this task in the near future.

**Comment by dariarostshina** [comment]
Hello!

We added it. Please download the last version of plugin.

**Comment by gonchik** [comment]
Thank you so much!
